// const processData = async () => {
//     throw new Error("Something went wrong");
// };
// const handleResult = async () => {
//     try {
//         const result = await processData();
//         console.log(result);
//     }
//     catch(error){
//         console.log(error.message);
//     }
// };
// handleResult();




// console.log(0.1+0.2 > 0.3);



